import { Campaign, Product, Insight, ChangeEvent, AISuggestion } from "./types";

// ─── Products ────────────────────────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "B0F4MPJWN2",
    asin: "B0F4MPJWN2",
    name: "LIME POOL 162 Pcs 7-Way Hot Tub, Spa & Pool Test Strips",
  },
  {
    id: "B0CHJ5BQHB",
    asin: "B0CHJ5BQHB",
    name: "Luxury Brisket & Carving Knife – Thoughtful Gifts for Men and Dad",
  },
  {
    id: "B0F3XG67VT",
    asin: "B0F3XG67VT",
    name: "Pool Skimmer Net – Deep Mesh, Reinforced Frame (Net only, No Pole) V01",
  },
  {
    id: "B0F3XHSYD1",
    asin: "B0F3XHSYD1",
    name: "Pool Skimmer Net – Deep Mesh, Reinforced Frame (Net only, No Pole) V02",
  },
  {
    id: "B0F7RJ1CB8",
    asin: "B0F7RJ1CB8",
    name: "Pool Skimmer Net for Cleaning – Heavy Duty Deep Mesh",
  },
];

// ─── AI Suggestions ──────────────────────────────────────────────────────────

function makeSuggestion(partial: Partial<AISuggestion> & { id: string; campaignId: string }): AISuggestion {
  return {
    type: "raise_bid",
    title: "Raise Bids to Recapture Top of Search",
    description: "Impressions dropped 38% after recent bid decrease. Raising bids may restore placement.",
    rationale: "Top of Search placement correlates with higher CVR for this product. Bid reduction cost us rank.",
    impact: "Est. +15–25% impressions, +10–18% orders",
    confidence: "High",
    recommendedValue: 2.80,
    currentValue: 2.24,
    unit: "$",
    status: "pending",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    ...partial,
  };
}

// ─── Campaigns ───────────────────────────────────────────────────────────────

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "c1",
    name: "PTS – SPT – CAT",
    type: "SP Manual",
    status: "Enabled",
    dailyBudget: 250,
    startDate: "2025-10-30",
    biddingStrategy: "Fixed Bid",
    portfolio: "MR – Pool Test Strips (PTS)",
    productIds: ["B0F4MPJWN2"],
    impressions: 1751,
    clicks: 41,
    orders: 11,
    units: 11,
    sales: 131.89,
    conversion: 26.83,
    spend: 91.86,
    cpc: 2.24,
    ctr: 2.34,
    acos: 69.65,
    roas: 1.44,
    prevImpressions: 2850,
    prevClicks: 68,
    prevOrders: 18,
    prevSales: 215.82,
    prevSpend: 112.40,
    prevAcos: 52.08,
    prevRoas: 1.92,
    aiSuggestions: [
      makeSuggestion({
        id: "s1",
        campaignId: "c1",
        type: "raise_bid",
        title: "Restore bids — ACOS rising after impression drop",
        description:
          "ACOS jumped from 52% → 70% while impressions fell 38%. This pattern suggests you lost Top of Search placement after a bid decrease.",
        recommendedValue: 2.70,
        currentValue: 2.24,
        confidence: "High",
      }),
    ],
  },
  {
    id: "c2",
    name: "PTS – SPT – hot tub test strips sv4968",
    type: "SP Manual",
    status: "Enabled",
    dailyBudget: 150,
    startDate: "2025-05-26",
    biddingStrategy: "Fixed Bid",
    portfolio: "MR – Pool Test Strips (PTS)",
    productIds: ["B0F4MPJWN2"],
    impressions: 951,
    clicks: 22,
    orders: 12,
    units: 12,
    sales: 143.88,
    conversion: 54.55,
    spend: 57.67,
    cpc: 2.62,
    ctr: 2.31,
    acos: 40.08,
    roas: 2.49,
    prevImpressions: 870,
    prevClicks: 20,
    prevOrders: 10,
    prevSales: 119.90,
    prevSpend: 51.20,
    prevAcos: 42.70,
    prevRoas: 2.34,
    aiSuggestions: [
      makeSuggestion({
        id: "s2",
        campaignId: "c2",
        type: "increase_budget",
        title: "Increase daily budget — campaign under-delivering",
        description: "Strong ROAS (2.49) with 54% CVR signals this campaign can scale. Budget may be capping delivery.",
        rationale: "Daily spend ($57) is well below $150 budget but impression velocity suggests budget isn't the limit. However, raising budget creates headroom for peak hours.",
        impact: "Est. +10–20% in spend efficiency",
        confidence: "Medium",
        recommendedValue: 200,
        currentValue: 150,
        unit: "$",
      }),
    ],
  },
  {
    id: "c3",
    name: "PTS – SPT – B09M5Y8BLB Easy test",
    type: "SP Manual",
    status: "Enabled",
    dailyBudget: 200,
    startDate: "2025-05-27",
    biddingStrategy: "Fixed Bid",
    portfolio: "MR – Pool Test Strips (PTS)",
    productIds: ["B0F4MPJWN2"],
    impressions: 2174,
    clicks: 20,
    orders: 5,
    units: 5,
    sales: 59.95,
    conversion: 25.0,
    spend: 42.69,
    cpc: 2.13,
    ctr: 0.92,
    acos: 71.21,
    roas: 1.40,
    prevImpressions: 2600,
    prevClicks: 31,
    prevOrders: 9,
    prevSales: 107.91,
    prevSpend: 59.83,
    prevAcos: 55.45,
    prevRoas: 1.80,
    aiSuggestions: [
      makeSuggestion({
        id: "s3",
        campaignId: "c3",
        type: "lower_bid",
        title: "Scale back bids — ACOS is 71%, CVR degrading",
        description:
          "Despite high impressions, CTR dropped to 0.92% and conversion fell. Keywords may now be attracting unqualified traffic.",
        rationale: "Broad match on 'easy test' may be capturing irrelevant searches. Consider tightening match types first.",
        impact: "Est. ACOS improvement to 50–55%",
        confidence: "Medium",
        recommendedValue: 1.80,
        currentValue: 2.13,
        unit: "$",
      }),
    ],
  },
  {
    id: "c4",
    name: "PTS – SPX – spa test strips for hot tub sv1762",
    type: "SP Manual",
    status: "Enabled",
    dailyBudget: 160,
    startDate: "2025-05-26",
    biddingStrategy: "Fixed Bid",
    portfolio: "MR – Pool Test Strips (PTS)",
    productIds: ["B0F4MPJWN2"],
    impressions: 1019,
    clicks: 9,
    orders: 4,
    units: 4,
    sales: 47.96,
    conversion: 44.44,
    spend: 21.27,
    cpc: 2.36,
    ctr: 0.88,
    acos: 44.35,
    roas: 2.25,
    prevImpressions: 980,
    prevClicks: 10,
    prevOrders: 4,
    prevSales: 47.96,
    prevSpend: 21.00,
    prevAcos: 43.79,
    prevRoas: 2.28,
    aiSuggestions: [],
  },
  {
    id: "c5",
    name: "PTS – SPX – spa test strips sv1443",
    type: "SP Manual",
    status: "Enabled",
    dailyBudget: 50,
    startDate: "2025-05-26",
    biddingStrategy: "Fixed Bid",
    portfolio: "MR – Pool Test Strips (PTS)",
    productIds: ["B0F4MPJWN2"],
    impressions: 458,
    clicks: 7,
    orders: 5,
    units: 5,
    sales: 59.95,
    conversion: 71.43,
    spend: 16.52,
    cpc: 2.36,
    ctr: 1.53,
    acos: 27.56,
    roas: 3.63,
    prevImpressions: 510,
    prevClicks: 9,
    prevOrders: 6,
    prevSales: 71.94,
    prevSpend: 18.90,
    prevAcos: 26.27,
    prevRoas: 3.81,
    aiSuggestions: [
      makeSuggestion({
        id: "s5",
        campaignId: "c5",
        type: "increase_budget",
        title: "Scale budget — best ROAS campaign (3.63x), low spend",
        description:
          "This is your highest ROAS campaign with a 71% CVR but only spending $16/day on a $50 budget. It can absorb more spend.",
        rationale: "Opportunity cost: If this campaign is under-delivering at peak hours, you're leaving profitable sales on the table.",
        impact: "Est. +$30–60/day in profitable spend",
        confidence: "High",
        recommendedValue: 100,
        currentValue: 50,
        unit: "$",
      }),
    ],
  },
  {
    id: "c6",
    name: "PTS – SPT – B077KK7V2R BS 2",
    type: "SP Manual",
    status: "Enabled",
    dailyBudget: 35,
    startDate: "2025-10-30",
    biddingStrategy: "Fixed Bid",
    portfolio: "MR – Pool Test Strips (PTS)",
    productIds: ["B0F4MPJWN2"],
    impressions: 1130,
    clicks: 4,
    orders: 2,
    units: 2,
    sales: 23.98,
    conversion: 50.0,
    spend: 7.74,
    cpc: 1.94,
    ctr: 0.35,
    acos: 32.28,
    roas: 3.10,
    prevImpressions: 1380,
    prevClicks: 6,
    prevOrders: 3,
    prevSales: 35.97,
    prevSpend: 10.32,
    prevAcos: 28.69,
    prevRoas: 3.48,
    aiSuggestions: [],
  },
  {
    id: "c7",
    name: "PTS – SPT – pool testing strips sv174",
    type: "SP Manual",
    status: "Enabled",
    dailyBudget: 30,
    startDate: "2025-05-26",
    biddingStrategy: "Fixed Bid",
    portfolio: "MR – Pool Test Strips (PTS)",
    productIds: ["B0F4MPJWN2"],
    impressions: 848,
    clicks: 4,
    orders: 1,
    units: 1,
    sales: 11.99,
    conversion: 25.0,
    spend: 12.16,
    cpc: 3.04,
    ctr: 0.47,
    acos: 101.42,
    roas: 0.99,
    prevImpressions: 920,
    prevClicks: 5,
    prevOrders: 2,
    prevSales: 23.98,
    prevSpend: 13.50,
    prevAcos: 56.30,
    prevRoas: 1.78,
    aiSuggestions: [
      makeSuggestion({
        id: "s7",
        campaignId: "c7",
        type: "lower_bid",
        title: "Urgently lower bids — ACOS >100%, ROAS <1",
        description:
          "This campaign is losing money: spending $12.16 to generate $11.99 in sales. CPC is highest in portfolio at $3.04.",
        rationale: "Possible causes: broad keywords, low-relevancy placement, or over-bid competition. Reduce bids first, then audit search terms.",
        impact: "Est. recovery to break-even ACOS (40–50%)",
        confidence: "High",
        recommendedValue: 1.80,
        currentValue: 3.04,
        unit: "$",
      }),
    ],
  },
  {
    id: "c8",
    name: "PTS – SPX – pool strips test sv189",
    type: "SP Manual",
    status: "Enabled",
    dailyBudget: 50,
    startDate: "2025-05-26",
    biddingStrategy: "Fixed Bid",
    portfolio: "MR – Pool Test Strips (PTS)",
    productIds: ["B0F4MPJWN2"],
    impressions: 185,
    clicks: 2,
    orders: 2,
    units: 2,
    sales: 23.98,
    conversion: 100.0,
    spend: 5.62,
    cpc: 2.81,
    ctr: 1.08,
    acos: 23.44,
    roas: 4.27,
    prevImpressions: 210,
    prevClicks: 3,
    prevOrders: 2,
    prevSales: 23.98,
    prevSpend: 7.11,
    prevAcos: 29.65,
    prevRoas: 3.37,
    aiSuggestions: [
      makeSuggestion({
        id: "s8",
        campaignId: "c8",
        type: "increase_budget",
        title: "Scale this campaign — 100% CVR, ROAS 4.27x, lowest spend",
        description:
          "Every click converts. At only $5.62 spend this campaign isn't being given enough runway. Scale budget and bids to capture more volume.",
        impact: "Potentially your highest ROI scaling opportunity",
        confidence: "High",
        recommendedValue: 100,
        currentValue: 50,
        unit: "$",
      }),
    ],
  },
];

// ─── Change Events ────────────────────────────────────────────────────────────

export const MOCK_CHANGE_EVENTS: ChangeEvent[] = [
  {
    id: "ch1",
    campaignId: "c1",
    campaignName: "PTS – SPT – CAT",
    changeType: "bid",
    field: "Default Bid",
    oldValue: 2.70,
    newValue: 2.24,
    changedAt: new Date(Date.now() - 8 * 24 * 3600000).toISOString(),
    changedBy: "user",
  },
  {
    id: "ch2",
    campaignId: "c3",
    campaignName: "PTS – SPT – B09M5Y8BLB Easy test",
    changeType: "bid",
    field: "Default Bid",
    oldValue: 2.50,
    newValue: 2.13,
    changedAt: new Date(Date.now() - 12 * 24 * 3600000).toISOString(),
    changedBy: "user",
  },
  {
    id: "ch3",
    campaignId: "c7",
    campaignName: "PTS – SPT – pool testing strips sv174",
    changeType: "budget",
    field: "Daily Budget",
    oldValue: 50,
    newValue: 30,
    changedAt: new Date(Date.now() - 5 * 24 * 3600000).toISOString(),
    changedBy: "user",
  },
];

// ─── Insights ─────────────────────────────────────────────────────────────────

export const MOCK_INSIGHTS: Insight[] = [
  {
    id: "i1",
    campaignId: "c1",
    campaignName: "PTS – SPT – CAT",
    category: "top_of_search_loss",
    severity: "critical",
    title: "Top of Search placement lost after bid decrease",
    whatChanged:
      "Impressions fell 38% (2,850 → 1,751) and ACOS worsened from 52% to 70% in 7 days. Sales dropped from $215 to $131.",
    likelyCause:
      "Bid was reduced from $2.70 → $2.24 on " +
      new Date(Date.now() - 8 * 24 * 3600000).toLocaleDateString() +
      ". This is consistent with losing Top of Search rank — competitors outbid you and impressions collapsed first, pulling sales down.",
    recommendedAction:
      "Partially restore bids to $2.60–$2.70 to test if impressions recover. Monitor Top of Search impression share in Placements report for 3–5 days before further adjustment.",
    confidence: "High",
    confidenceScore: 87,
    metrics: [
      { label: "Impressions", current: 1751, previous: 2850, change: -38.6, unit: "" },
      { label: "ACOS", current: 69.65, previous: 52.08, change: 33.7, unit: "%" },
      { label: "Sales", current: 131.89, previous: 215.82, change: -38.9, unit: "$" },
      { label: "ROAS", current: 1.44, previous: 1.92, change: -25.0, unit: "x" },
    ],
    structuredAction: {
      id: "ia1",
      campaignId: "c1",
      type: "raise_bid",
      title: "Restore bids to $2.65",
      description: "Raise default bid from $2.24 → $2.65 to recapture Top of Search impression share",
      rationale: "Bid reduction on " + new Date(Date.now() - 8 * 24 * 3600000).toLocaleDateString() + " correlates with 38% impression drop",
      impact: "Est. +30–40% impression recovery, ACOS normalization to 50–55%",
      confidence: "High",
      recommendedValue: 2.65,
      currentValue: 2.24,
      unit: "$",
      status: "pending",
      createdAt: new Date().toISOString(),
    },
    relatedChangeEvent: MOCK_CHANGE_EVENTS[0],
    detectedAt: new Date().toISOString(),
  },
  {
    id: "i2",
    campaignId: "c7",
    campaignName: "PTS – SPT – pool testing strips sv174",
    category: "over_optimized",
    severity: "critical",
    title: "Campaign ACOS above 100% — losing money on every sale",
    whatChanged:
      "ACOS spiked from 56% → 101% in 7 days. ROAS dropped below 1x ($0.99). Spending $12.16 to generate $11.99.",
    likelyCause:
      "CPC rose to $3.04 (highest in portfolio) while CVR held at 25%. Either bids are too high for current competition, or broad search terms are attracting irrelevant clicks.",
    recommendedAction:
      "Lower bids immediately to $1.80–$2.00. Audit search term report — add negatives for irrelevant terms. Check if placement is Top of Search vs. Rest of Search (ROS clicks convert worse).",
    confidence: "High",
    confidenceScore: 92,
    metrics: [
      { label: "ACOS", current: 101.42, previous: 56.30, change: 80.1, unit: "%" },
      { label: "ROAS", current: 0.99, previous: 1.78, change: -44.4, unit: "x" },
      { label: "CPC", current: 3.04, previous: 2.70, change: 12.6, unit: "$" },
      { label: "Sales", current: 11.99, previous: 23.98, change: -50.0, unit: "$" },
    ],
    structuredAction: {
      id: "ia2",
      campaignId: "c7",
      type: "lower_bid",
      title: "Lower bids to $1.80 — campaign unprofitable",
      description: "Reduce default bid from $3.04 → $1.80 to stop hemorrhaging spend",
      rationale: "ACOS >100% means every sale loses money. Immediate action required.",
      impact: "Est. ACOS recovery to 50–60% within 5–7 days",
      confidence: "High",
      recommendedValue: 1.80,
      currentValue: 3.04,
      unit: "$",
      status: "pending",
      createdAt: new Date().toISOString(),
    },
    relatedChangeEvent: MOCK_CHANGE_EVENTS[2],
    detectedAt: new Date().toISOString(),
  },
  {
    id: "i3",
    campaignId: "c5",
    campaignName: "PTS – SPX – spa test strips sv1443",
    category: "over_optimized",
    severity: "opportunity",
    title: "ACOS improved but volume is declining — possible over-optimization",
    whatChanged:
      "ACOS improved from 26% → 27% (stable), but impressions fell 10% and orders dropped from 6 → 5. Revenue slipped from $72 → $60.",
    likelyCause:
      "Previous period had stronger impression velocity. While ACOS looks OK, declining volume suggests bids may be slightly below the market clearing price for this keyword cluster.",
    recommendedAction:
      "Test a 5–10% bid increase. ROAS is strong (3.63x) and CVR (71%) is exceptional — this campaign can absorb slightly higher CPCs and still be profitable.",
    confidence: "Medium",
    confidenceScore: 68,
    metrics: [
      { label: "Impressions", current: 458, previous: 510, change: -10.2, unit: "" },
      { label: "Orders", current: 5, previous: 6, change: -16.7, unit: "" },
      { label: "Sales", current: 59.95, previous: 71.94, change: -16.7, unit: "$" },
      { label: "ROAS", current: 3.63, previous: 3.81, change: -4.7, unit: "x" },
    ],
    structuredAction: {
      id: "ia3",
      campaignId: "c5",
      type: "raise_bid",
      title: "Test bid increase to $2.60",
      description: "Raise bid from $2.36 → $2.60 (+10%) to recapture lost impression share",
      rationale: "CVR (71%) and ROAS (3.63x) are strong enough to absorb a modest bid increase",
      impact: "Est. +10–15% impression recovery, +1–2 additional orders per week",
      confidence: "Medium",
      recommendedValue: 2.60,
      currentValue: 2.36,
      unit: "$",
      status: "pending",
      createdAt: new Date().toISOString(),
    },
    detectedAt: new Date().toISOString(),
  },
  {
    id: "i4",
    campaignId: "c8",
    campaignName: "PTS – SPX – pool strips test sv189",
    category: "improving",
    severity: "opportunity",
    title: "100% conversion rate — scale this campaign immediately",
    whatChanged:
      "CVR improved from previous period and ROAS jumped from 3.37x → 4.27x. Every click is converting to a sale.",
    likelyCause:
      "High-intent, exact or phrase match keywords are capturing buyers very late in their purchase journey. This is the most efficient campaign in the portfolio.",
    recommendedAction:
      "Double the daily budget ($50 → $100) and raise bids slightly (+10%) to capture more of these high-intent searches. This is your best scaling opportunity.",
    confidence: "High",
    confidenceScore: 91,
    metrics: [
      { label: "CVR", current: 100, previous: 66.7, change: 49.9, unit: "%" },
      { label: "ROAS", current: 4.27, previous: 3.37, change: 26.7, unit: "x" },
      { label: "ACOS", current: 23.44, previous: 29.65, change: -20.9, unit: "%" },
      { label: "Spend", current: 5.62, previous: 7.11, change: -21.0, unit: "$" },
    ],
    structuredAction: {
      id: "ia4",
      campaignId: "c8",
      type: "increase_budget",
      title: "Double budget to $100 + raise bids 10%",
      description: "Increase daily budget from $50 → $100 and raise bids from $2.81 → $3.10",
      rationale: "100% CVR and 4.27x ROAS make this the highest-priority scaling candidate",
      impact: "Est. 2x spend with same or better ROAS — $10–20/day in additional profit",
      confidence: "High",
      recommendedValue: 100,
      currentValue: 50,
      unit: "$",
      status: "pending",
      createdAt: new Date().toISOString(),
    },
    detectedAt: new Date().toISOString(),
  },
  {
    id: "i5",
    campaignId: "c3",
    campaignName: "PTS – SPT – B09M5Y8BLB Easy test",
    category: "declining",
    severity: "warning",
    title: "Previously strong campaign declining across all metrics",
    whatChanged:
      "Impressions fell 16% (2,600 → 2,174), clicks dropped 35% (31 → 20), orders collapsed 44% (9 → 5). ACOS worsened from 55% → 71%.",
    likelyCause:
      "Bid reduction on " + new Date(Date.now() - 12 * 24 * 3600000).toLocaleDateString() + " ($2.50 → $2.13) likely caused rank loss across multiple keywords. The cumulative effect of lower rank is showing up as both lower CTR and lower CVR.",
    recommendedAction:
      "Partially restore bids to $2.35–$2.40. Audit keyword-level performance — some keywords may need individual bid increases while others can stay lower.",
    confidence: "High",
    confidenceScore: 82,
    metrics: [
      { label: "Impressions", current: 2174, previous: 2600, change: -16.4, unit: "" },
      { label: "Clicks", current: 20, previous: 31, change: -35.5, unit: "" },
      { label: "Orders", current: 5, previous: 9, change: -44.4, unit: "" },
      { label: "ACOS", current: 71.21, previous: 55.45, change: 28.4, unit: "%" },
    ],
    structuredAction: {
      id: "ia5",
      campaignId: "c3",
      type: "raise_bid",
      title: "Partially restore bids to $2.38",
      description: "Raise default bid from $2.13 → $2.38 as a measured recovery step",
      rationale: "Bid reduction correlates directly with multi-metric decline across impressions, CTR, and CVR",
      impact: "Est. ACOS recovery to 55–60% within 7 days",
      confidence: "High",
      recommendedValue: 2.38,
      currentValue: 2.13,
      unit: "$",
      status: "pending",
      createdAt: new Date().toISOString(),
    },
    relatedChangeEvent: MOCK_CHANGE_EVENTS[1],
    detectedAt: new Date().toISOString(),
  },
];
